name: for_practice
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/Assets/images/

  fonts:
    - family: Kenia
      fonts:
        - asset: lib/Assets/fonts/Kenia-Regular.ttf
    - family: Lato
      fonts:
        - asset: lib/Assets/fonts/Lato-Black.ttf
